import { Inter } from 'next/font/google';
import './globals.css';
import Header from '@/components/Header';
import toast, { Toaster } from 'react-hot-toast';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body className={` ${inter.className}`}>
        {/* <Header /> */}
        <Toaster position="top-center" reverseOrder={false} containerStyle={{
          top: '50%',
          left: '50%',
          transform: 'translate(-50%, -50%)',
          width: '1000px',
        }} />
        {children}
      </body>
    </html>
  );
}
